@startuml main
' 잇츠업(eat's up) 서비스 유즈케이스 다이어그램
' 작성자 : 장보명
' 작성일 : 23.09.05
' desc :
/'
    관계 표기
    include = in
    intends = in
'/
left to right direction
:비회원: --- (회원가입)
:회원: --- (인증)

:회원: --- (친구 목록 보기)

:회원: --- (마이페이지)

:회원: --- (리뷰 게시글 작성)
:회원: --- (리뷰 지도 보기)
:회원: --- (게시판 보기)


:회원: --- (랭킹 보기)

(댓글 보기)-->(리뷰 보기)
(리뷰 보기) ..> (게시판 보기)


:관리자: --- (가게 관리)
(가게 정보 삭제) --> (가게 관리)
(가게 정보 수정) --> (가게 관리)
(가게 삭제) --> (가게 관리)

:관리자: --- (회원 관리)
(회원 조회) --> (회원 관리)
(회원 정지) --> (회원 관리)

(회원 정보 수정) --> (회원 관리)

:관리자: --- (현황 조회) 
(가입 현황 조회) --> (현황 조회)
(맛집 현황 조회) --> (현황 조회)
(리뷰 현황 조회) --> (현황 조회)

/'
:회원: --- (검색)
(검색) ..> (인증) : in
(지역 검색) ..> (검색): ex
'/

@enduml
