@startuml
' Rest Area 유즈케이스 다이어그램
' 작성자 : 장보명
' 작성일 : 23.11.26
' desc : 실제 Rest Area Core Site 와 각 서비스간의 관계만 개략적으로 표시
/'
    관계 표기
    include = in
    intends = in
'/
left to right direction
:비회원: --- (회원가입)
:회원: --- (인증)
(리뷰 게시글 작성) ..> (인증) : in
(피드 목록 보기) ..>(인증) : in
(리뷰 지도 보기) ..> (인증) : in
(회원 개인 정보 보기) ..> (회원 기본 정보) : in
(리뷰 작성자 정보 보기) ..> (회원 기본 정보) :in

package RestAreaService {
    usecase "회원가입" as Join
    usecase "로그인" as Login

    package 메일서비스 {    
        
        usecase "메일 전송" as MailSend
        usecase "메일 목록 보기" as MailListView
    }
    package 클라우드서비스 {
        usecase "메일 전송 API" as MailSendAPI
        usecase "메일 전송 목록 API" as MailSendHistoryAPI

    }
}


' :회원: --> 메일발송

:회원: --- (친구 목록 보기)
(회원 검색) ..> (친구 목록 보기) : ex
(친구 추가) ..> (친구 목록 보기) : ex

(친구 삭제) ..> (친구 목록 보기) : ex
:회원: --- (회원 개인 정보 보기)
(회원 기본 정보) ..> (인증) : in

:회원: --- (리뷰 게시글 작성)
:회원: --- (리뷰 지도 보기)
:회원: --- (피드 목록 보기)

(리뷰 지도 보기) <.. (가게 정보 보기) : ex
:회원: --- (랭킹 보기)
(랭킹 보기) ..> (인증) : in
(댓글 보기)-->(리뷰 보기)


(리뷰 보기) ..> (피드 목록 보기) : ex
:관리자: --- (가게 관리)
(가게 정보 삭제) --> (가게 관리)
(가게 정보 수정) --> (가게 관리)
(가게 삭제) --> (가게 관리)
(리뷰 보기) <.. (가게 정보 보기) : ex
(댓글 삭제) ..> (리뷰 보기) : ex
(댓글 수정) ..> (리뷰 보기) : ex
(댓글 추천) ..> (리뷰 보기) : ex
:관리자: --- (회원 관리)
(회원 조회) --> (회원 관리)
(회원 정지) --> (회원 관리)
(리뷰 보기) <.. (리뷰 작성자 정보 보기) : ex
(회원 정보 수정) --> (회원 관리)
(친구 목록 보기) ..> (인증)
:관리자: --- (현황 조회) 
(가입 현황 조회) --> (현황 조회)
(맛집 현황 조회) --> (현황 조회)
(리뷰 현황 조회) --> (현황 조회)
(현황 조회) ..> (인증) : in
/'
:회원: --- (검색)
(검색) ..> (인증) : in
(지역 검색) ..> (검색): ex
'/
(회원 관리) ..> (인증) : in
(가게 관리) ..> (인증) : in
@enduml
